### ISSUE TITLE
NewTestMap corrupted, causing Serialization Error

### ISSUE THREAD

**Issue by BlueprintBailey** [YakuzaBalooza/Dash-Engine-1.3#3]
@YakuzaBalooza, I think that your level is causing the project to be corrupted. I actually got the project to port for UE5.1, but that one level map always causes issues and crashes.

I know it's probably not an issue you had, but hopefully you can make sure that the one level map isn't corrupted.

Thanks anyways.

**Comment by YakuzaBalooza** [comment]
Like with the prior Issue, I'm unable to do a port or develop for UE5 in mind for Dash Engine 1.3. The thing that's causing errors is likely actors within NewTestMap attempting to reference or display Cascade particles, which don't exist in UE5 (replaced by Niagara).
Again, your best bet is to compile for **UE4.27**, not UE5.
