### ISSUE TITLE
[Bug?] DashEngine cannot compile after module DiscordRPC is installed.

### ISSUE THREAD

**Issue by ViviNoSmol** [YakuzaBalooza/Dash-Engine-1.3#4]
I tried to install DiscordRPC plugin ([this one](https://github.com/ryanjon2040/Discord-UE4))
And after compiling the modules for that plugin, it requires DashEngine to compile again, the problem is that everytime it does that, it throws the "DashEngine couldn't be compiled"

**Comment by YakuzaBalooza** [comment]
Not sure why Dash Engine fails to compile when using a plugin. I've installed plugins before on older projects using Dash Engine via the Epic Launcher and those worked fine.
I would double check to ensure that the plugin is properly installed, and also make sure VS is setup correctly.
Will close this for now as I sadly don't have the time to try and reproduce this issue. My apologies.
